//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoomezSearch.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoomezSearch.App_GlobalResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean: {0}?.
        /// </summary>
        internal static string didYouMean {
            get {
                return ResourceManager.GetString("didYouMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops!, It seems we&apos;re having a little problem there. Don&apos;t worry, we&apos;re working on it :).
        /// </summary>
        internal static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feeling Lucky?.
        /// </summary>
        internal static string feelingLucky {
            get {
                return ResourceManager.GetString("feelingLucky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp support.
        /// </summary>
        internal static string ftpSupport {
            get {
                return ResourceManager.GetString("ftpSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goomez History.
        /// </summary>
        internal static string goomezHistory {
            get {
                return ResourceManager.GetString("goomezHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goomez Search.
        /// </summary>
        internal static string goomezSearch {
            get {
                return ResourceManager.GetString("goomezSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string goomezStore {
            get {
                return ResourceManager.GetString("goomezStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Goomez Home Page.
        /// </summary>
        internal static string goToGoomez {
            get {
                return ResourceManager.GetString("goToGoomez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History Search.
        /// </summary>
        internal static string historySearch {
            get {
                return ResourceManager.GetString("historySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IE8 Goomez Activity.
        /// </summary>
        internal static string ieActivity {
            get {
                return ResourceManager.GetString("ieActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install IE8 Goomez Activity.
        /// </summary>
        internal static string installIE8Activity {
            get {
                return ResourceManager.GetString("installIE8Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!, nothing found for &apos;{0}&apos;, please refine your search.
        /// </summary>
        internal static string noResults {
            get {
                return ResourceManager.GetString("noResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string openFolder {
            get {
                return ResourceManager.GetString("openFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        internal static string pager {
            get {
                return ResourceManager.GetString("pager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results for &apos;{1}&apos; ({2} seconds).
        /// </summary>
        internal static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History for {0}.
        /// </summary>
        internal static string searchHistoryFor {
            get {
                return ResourceManager.GetString("searchHistoryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        internal static string searchHistoy {
            get {
                return ResourceManager.GetString("searchHistoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Search Provider.
        /// </summary>
        internal static string searchProvider {
            get {
                return ResourceManager.GetString("searchProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Goomez Search as an IE search provider.
        /// </summary>
        internal static string searchProviderToolTip {
            get {
                return ResourceManager.GetString("searchProviderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to try with {0}? ({1}).
        /// </summary>
        internal static string tryGoogle {
            get {
                return ResourceManager.GetString("tryGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download user.js file.
        /// </summary>
        internal static string userJsToolTip {
            get {
                return ResourceManager.GetString("userJsToolTip", resourceCulture);
            }
        }
    }
}
